### ISSUE TITLE
How do I use this code

### ISSUE THREAD

**Issue by GUZ-lkc2018** [younesidsouguou/LiDAR_Object_Detection#1]
Thank you very much for sharing this code，How do I learn your code? Could you give me a guide?

**Comment by younesidsouguou** [comment]
Hello,

I would like to thank you for your interest in this repository. 

Actually, my code is self explanatory based on the organisation of the script. Otherwise, it was a lot about handling arrays and more specifically NumPy arrays. So a point cloud is treated as a 3 by n matrix. Hopefully you find this helpful.

Regards,

**Comment by GUZ-lkc2018** [comment]
Ok,thank you.
